In [1]:
import sys
sys.path.append("../common")

from m_dataLoad_json import *

In [2]:
root_dir='../../dvc_olivas_clasificacion_vistas/data/2022'
dataplaces=[('jsons','images')]

suffixes=['_r.png','_g.png','_b.png','_a.png','_nir.png','_nir1.png','_nir2.png','_nir4.png']
num_channels_in=len(suffixes)
max_value=1024
tipos_defecto=[ "agostado",  "envero","escudete", "granizo","molestadograve", "molestadoleve",  "morada", "negra","picadamosca"]

In [3]:
trainset,valset,tipos_defecto=genera_ds_jsons_multilabel(root=root_dir,  dataplaces=dataplaces, sufijos=suffixes,max_value=255, prob_train=0.8,crop_size=(120,120),defect_types=tipos_defecto,splitname_delimiter='_',
                               multilabel=True, in_memory=False)



Tipos de Defecto por configuracion: ['agostado', 'envero', 'escudete', 'granizo', 'molestadograve', 'molestadoleve', 'morada', 'negra', 'picadamosca']


In [4]:
fruitids=[]
viewids=[]
for v in trainset:
    #print(v['view_id'])
    fruitids.append(v['fruit_id'])
    viewids.append(v['view_id'])
fruitids_train = set(fruitids)
viewids_train=set(viewids)


fruitids=[]
viewids=[]
for v in valset:
    #print(v['view_id'])
    fruitids.append(v['fruit_id'])
    viewids.append(v['view_id'])    
fruitids_val = set(fruitids)
viewids_val=set(viewids)



In [5]:
print(fruitids_train.intersection(fruitids_val))
print(viewids_train.intersection(viewids_val))
print(len(viewids_train), len(viewids_val))

set()
set()
5909 1448


In [6]:
# Find missing labels

trainset[0]

{'fruit_id': '20221117_1448_000870',
 'view_id': '20221117_1448_000870_04',
 'image': None,
 'labels': tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 'imag_folder': '../../dvc_olivas_clasificacion_vistas/data/2022/images',
 'sufijos': ['_r.png',
  '_g.png',
  '_b.png',
  '_a.png',
  '_nir.png',
  '_nir1.png',
  '_nir2.png',
  '_nir4.png'],
 'max_value': 255,
 'crop_size': (120, 120)}

In [7]:
for v in valset:
    labels=v['labels']
    nanlabels=torch.isnan(labels).any()
    print(labels)
    neglabels=(labels<0).any()

    if nanlabels or neglabels:
        print(v)

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([1., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0.

In [8]:
train_jsons=list(viewids_train)
train_jsons=[v+'.json' for v in train_jsons]

val_jsons=list(viewids_val)
val_jsons=[v+'.json' for v in val_jsons]

In [9]:
print(len(train_jsons),len(val_jsons))

5909 1448


In [27]:
train_jsons[:5]

['20221117_1407_000597_03.json',
 '20221117_1451_001116_00.json',
 '20221117_1409_000735_05.json',
 '20221117_1447_000849_00.json',
 '20221117_1450_001051_01.json']

In [34]:
import os
import pathlib
root_dir='/home/aalbiol/owc/mscanData/pngs_anotados/Smart4Olives/season_2022/manzanilla/Season_oct_2022_set01_rev1'
out_train_dir=os.path.join(root_dir,'split_jsons/train')
out_val_dir=os.path.join(root_dir,'split_jsons/val')
split_dir=os.path.join(root_dir,'split_jsons')
source_dir=os.path.join(root_dir,'annotations')

pathlib.Path.mkdir(split_dir,exist_ok=True)
pathlib.Path.mkdir(out_train_dir,exist_ok=True)
pathlib.Path.mkdir(out_val_dir,exist_ok=True)

In [37]:
import shutil
for j in train_jsons:
    source_file=os.path.join(source_dir, j)
    target_file=os.path.join(out_train_dir, j)
    shutil.copy(source_file,target_file)
    #print(source_file, '-->', target_file)
    print(j)

import shutil
for j in val_jsons:
    source_file=os.path.join(source_dir, j)
    target_file=os.path.join(out_val_dir, j)
    shutil.copy(source_file,target_file)
    #print(source_file, '-->', target_file)
    print(j)

20221117_1407_000597_03.json
20221117_1451_001116_00.json
20221117_1409_000735_05.json
20221117_1447_000849_00.json
20221117_1450_001051_01.json
20221117_1406_000558_00.json
20221117_1343_000104_03.json
20221117_1505_001330_02.json
20221117_1448_000861_01.json
20221117_1342_000063_05.json
20221117_1504_001252_04.json
20221117_1343_000094_01.json
20221117_1401_000439_02.json
20221117_1406_000565_03.json
20221117_1523_001542_00.json
20221117_1450_001062_01.json
20221117_1343_000136_05.json
20221117_1401_000424_04.json
20221117_1408_000679_03.json
20221117_1449_000966_05.json
20221117_1401_000425_03.json
20221117_1450_001061_05.json
20221117_1505_001322_01.json
20221117_1536_001858_05.json
20221117_1543_000204_05.json
20221117_1410_000788_04.json
20221117_1527_001782_00.json
20221117_1505_001291_00.json
20221117_1503_001194_05.json
20221117_1342_000067_01.json
20221117_1505_001286_01.json
20221117_1343_000093_01.json
20221117_1538_001973_02.json
20221117_1524_001591_04.json
20221117_1543_

In [11]:
import torch
import math

torch.isnan(torch.tensor([1,math.nan]))

tensor([False,  True])